spring.application.name=vcledger
spring.datasource.url=jdbc:mysql://localhost:3306/vcledger
spring.datasource.username=user1
spring.datasource.password=pass1

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


jwt.secret=h/UXrYxwCaSe5Z2Ny+r1SBQkX2i9omXwXmoP3ndSX2w=
jwt.expiration=36000000

logging.level.org.springframework.security=TRACE

savram-api-key=${SAVRAM_API_KEY}

groq.api-key=${GROQ_API_KEY}
groq.model=openai/gpt-oss-120b


cloudinary.cloud-name=ql8vhy6a
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}