spring.application.name=vcledger
spring.datasource.url=jdbc:mysql://localhost:3306/vcledger
spring.datasource.username=user1
spring.datasource.password=pass1

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


jwt.secret=h/UXrYxwCaSe5Z2Ny+r1SBQkX2i9omXwXmoP3ndSX2w=
jwt.expiration=36000000

logging.level.org.springframework.security=TRACE