spring.application.name=vcledger
server.port=${PORT:8080}

spring.datasource.url=${NEON_DB_VCLEDGER_URL}
spring.datasource.username=${NEON_DB_VCLEDGER_USERNAME}
spring.datasource.password=${NEON_DB_VCLEDGER_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true


jwt.secret=${VCLEDGER_JWT_SECRET}
jwt.expiration=36000000

#logging.level.org.springframework.security=TRACE

savram-api-key=${SAVRAM_API_KEY}

groq.api-key=${GROQ_API_KEY}
groq.model=openai/gpt-oss-120b


cloudinary.cloud-name=ql8vhy6a
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}